
CREATE TABLE `alarmSystem` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `siteID` INT NOT NULL,
  `deviceID` INT NOT NULL,
  `locationDescriptor` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `doorbell` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `siteID` INT NOT NULL,
  `deviceID` INT NOT NULL,
  `locationDescriptor` VARCHAR(255) NOT NULL,
  `doorbellStatus` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `doorSensor` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `siteID` INT NOT NULL,
  `deviceID` INT NOT NULL,
  `locationDescriptor` VARCHAR(255) NOT NULL,
  `sensorStatus` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `humTemp` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `siteID` INT NOT NULL,
  `deviceID` INT NOT NULL,
  `locationDescriptor` VARCHAR(255) NOT NULL,
  `temperature` FLOAT NOT NULL,
  `humidity` FLOAT NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `lightSwitch` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `siteID` INT NOT NULL,
  `deviceID` INT NOT NULL,
  `locationDescriptor` VARCHAR(255) NOT NULL,
  `switchUsed` VARCHAR(255) NOT NULL,
  `switchState` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `loRaWAN` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `timestamp` BIGINT NOT NULL,
  `devID` VARCHAR(255) NOT NULL,
  `siteID` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `unit` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- AUTO_INCREMENT for dumped tables
ALTER TABLE `alarmSystem` AUTO_INCREMENT = 1;
ALTER TABLE `doorbell` AUTO_INCREMENT = 1;
ALTER TABLE `doorSensor` AUTO_INCREMENT = 1;
ALTER TABLE `humTemp` AUTO_INCREMENT = 1;
ALTER TABLE `lightSwitch` AUTO_INCREMENT = 1;
ALTER TABLE `loRaWAN` AUTO_INCREMENT = 1;

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
